"""Adapter-agnostic source ingestion framework boundary."""

from .contracts import (
    CanonicalFilterOutcome,
    ErrorCategory,
    ErrorClassification,
    EvidenceRef,
    FetchContext,
    FetchOutcome,
    KnownOfferIndex,
    PaginationSupport,
    ProviderExecutionPlan,
    RawCapture,
    RawCaptureOrigin,
    RawOfferHandoff,
    RawTrace,
    RateLimitObservation,
    RateLimitSupport,
    ReferenceDatasetSnapshot,
    SourceAdapter,
    SourceCapabilities,
    TimeWindowSupport,
)
from .data_loader import CuratedDatasets, HybridCityRecord, KnownCompanyRecord, load_curated_datasets
from .models import (
    CanonicalOfferSnapshot,
    CanonicalRunTrace,
    FilterIntent,
    IngestionJob,
    IngestionRun,
    RetryRecord,
    RunCounters,
    RunStatus,
)
from .orchestrator import (
    IngestionGuardrails,
    IngestionOrchestrator,
    OrchestrationResult,
)
from .search_strategy import CaptureProfile, build_capture_profile, build_provider_execution_plan, evaluate_offer

__all__ = [
    "ErrorCategory",
    "ErrorClassification",
    "EvidenceRef",
    "FetchContext",
    "FetchOutcome",
    "FilterIntent",
    "CanonicalFilterOutcome",
    "CanonicalOfferSnapshot",
    "CanonicalRunTrace",
    "CaptureProfile",
    "CuratedDatasets",
    "HybridCityRecord",
    "IngestionGuardrails",
    "IngestionJob",
    "IngestionOrchestrator",
    "IngestionRun",
    "KnownCompanyRecord",
    "KnownOfferIndex",
    "OrchestrationResult",
    "PaginationSupport",
    "ProviderExecutionPlan",
    "RawCapture",
    "RawCaptureOrigin",
    "RawOfferHandoff",
    "RawTrace",
    "RateLimitObservation",
    "RateLimitSupport",
    "ReferenceDatasetSnapshot",
    "RetryRecord",
    "RunCounters",
    "RunStatus",
    "SourceAdapter",
    "SourceCapabilities",
    "TimeWindowSupport",
    "build_capture_profile",
    "build_provider_execution_plan",
    "evaluate_offer",
    "load_curated_datasets",
]
